#!/usr/bin/env python3

# The MIT License (MIT)
# Copyright (c) 2018 - Universidad del Cauca, Juan Ruiz-Rosero
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
# DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
# OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
# OR OTHER DEALINGS IN THE SOFTWARE.

import sys
import os
import json
import csv
import threading
import webbrowser

import matplotlib
matplotlib.use('QtAgg')

from PySide6.QtWidgets import (
    QApplication, QMainWindow, QWidget, QTabWidget,
    QVBoxLayout, QHBoxLayout, QFormLayout,
    QLabel, QLineEdit, QPushButton, QCheckBox,
    QComboBox, QSpinBox, QPlainTextEdit, QSplitter,
    QDialog, QProgressBar, QFileDialog, QMessageBox,
    QMenuBar, QSizePolicy, QSpacerItem,
    QTableWidget, QTableWidgetItem, QHeaderView,
)
from PySide6.QtGui import QPixmap, QIcon, QAction, QActionGroup, QPalette, QColor, QKeySequence, QShortcut
from PySide6.QtCore import Qt, QTimer

import globalVar
from PreProcessClass import PreProcessClass
from ScientoPyClass import ScientoPyClass, ScientoPyError
from generateBibtex import generateBibtex

def asset_path(filename):
    """Resolve asset path for both PyInstaller bundle and source mode."""
    if getattr(sys, 'frozen', False):
        base = sys._MEIPASS
    else:
        base = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(base, filename)

CONFIG_FILE = "scientopy_config.json"

HEADER_TOOLTIPS = {
    # Analysis results headers
    "Pos.": "Position in the ranking",
    "Total": "Total number of documents",
    "AGR": "Average Growth Rate: average difference between documents\n"
           "published in one year and the previous year, inside a time frame.\n"
           "AGR = \u03a3(Pi - Pi-1) / (Ye - Ys + 1)",
    "ADY": "Average Documents per Year: average number of documents\n"
           "published inside a time frame for a specific topic.\n"
           "ADY = \u03a3Pi / (Ye - Ys + 1)",
    "PDLY": "Percentage of Documents in Last Years: percentage of the ADY\n"
            "relative to the total number of documents for a specific topic.\n"
            "PDLY = (\u03a3Pi / ((Ye - Ys + 1) * TND)) * 100%",
    "hIndex": "h-index: a topic has index h if h of its documents have\n"
              "been cited at least h times",
    # Preprocess brief headers
    "Info": "Description of the preprocessing statistic",
    "Number": "Count of documents",
    "Percentage": "Relative percentage",
    "Source": "Database source (WoS or Scopus)",
    # Extended results headers
    "Cited by": "Number of citations received by the document",
    "EID": "Document unique identifier (from WoS or Scopus)",
    "EID2": "Secondary document identifier",
    "Year": "Publication year of the document",
    "Title": "Title of the document",
    "Document type": "Type of document (Conference Paper, Article, Review, etc.)",
    "Authors": "Document authors list",
    "Author keywords": "Keywords assigned by the document authors",
    "Both keywords": "Author keywords and index keywords combined",
    # Criterion headers (both original and capitalized CSV column names)
    "author": "Authors last name and first name initial",
    "Author": "Authors last name and first name initial",
    "sourceTitle": "Journal name",
    "SourceTitle": "Journal name",
    "subject": "Research area (only from WoS documents)",
    "Subject": "Research area (only from WoS documents)",
    "abstract": "Document's abstract",
    "Abstract": "Document's abstract",
    "authorKeywords": "Author's keywords",
    "AuthorKeywords": "Author's keywords",
    "indexKeywords": "Keywords generated by the index. From WoS {Keyword Plus},\n"
                     "and from Scopus {Indexed keywords}",
    "IndexKeywords": "Keywords generated by the index. From WoS {Keyword Plus},\n"
                     "and from Scopus {Indexed keywords}",
    "bothKeywords": "AuthorKeywords and indexKeywords combined",
    "BothKeywords": "AuthorKeywords and indexKeywords combined",
    "documentType": "Type of document",
    "DocumentType": "Type of document",
    "dataBase": "Database where the document was extracted (WoS or Scopus)",
    "DataBase": "Database where the document was extracted (WoS or Scopus)",
    "country": "Country extracted from authors affiliations",
    "Country": "Country extracted from authors affiliations",
    "institution": "Institution extracted from authors affiliations\n"
                   "(only from WoS documents)",
    "Institution": "Institution extracted from authors affiliations\n"
                   "(only from WoS documents)",
    "institutionWithCountry": "Institution with country extracted from\n"
                              "authors affiliations",
    "InstitutionWithCountry": "Institution with country extracted from\n"
                              "authors affiliations",
}

DARK_MATPLOTLIB_STYLE = {
    'figure.facecolor': '#2b2b2b',
    'axes.facecolor': '#2b2b2b',
    'axes.edgecolor': '#cccccc',
    'axes.labelcolor': '#cccccc',
    'text.color': '#cccccc',
    'xtick.color': '#cccccc',
    'ytick.color': '#cccccc',
    'grid.color': '#555555',
}


def load_config():
    defaults = {
        "appearance_mode": "System",
        "last_dataset_folder": "",
        "window_geometry": "1000x600",
        "splitter_sizes": [280, 600],
    }
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r") as f:
                saved = json.load(f)
            defaults.update(saved)
        except Exception:
            pass
    return defaults


def save_config(config):
    try:
        with open(CONFIG_FILE, "w") as f:
            json.dump(config, f, indent=4)
    except Exception:
        pass


def is_dark_mode(app):
    palette = app.palette()
    bg = palette.color(QPalette.ColorRole.Window)
    return bg.lightnessF() < 0.5


def apply_matplotlib_theme(app):
    if is_dark_mode(app):
        matplotlib.rcParams.update(DARK_MATPLOTLIB_STYLE)
    else:
        matplotlib.rcParams.update(matplotlib.rcParamsDefault)
        matplotlib.rcParams['figure.dpi'] = 100


class NumericTableWidgetItem(QTableWidgetItem):
    def __lt__(self, other):
        try:
            return float(self.text()) < float(other.text())
        except ValueError:
            return super().__lt__(other)


class ProgressDialog(QDialog):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.setWindowModality(Qt.WindowModal)
        self.setFixedSize(350, 140)
        self.setWindowTitle("Progress")

        layout = QVBoxLayout(self)

        self.label = QLabel("Starting...")
        self.label.setAlignment(Qt.AlignCenter)
        layout.addWidget(self.label)

        self.progress_bar = QProgressBar()
        self.progress_bar.setRange(0, 100)
        layout.addWidget(self.progress_bar)

        self.cancel_button = QPushButton("Cancel")
        self.cancel_button.clicked.connect(self.on_cancel)
        layout.addWidget(self.cancel_button, alignment=Qt.AlignCenter)

        self.timer = QTimer(self)
        self.timer.timeout.connect(self.update_progress)
        self.timer.start(100)

    def update_progress(self):
        self.label.setText(globalVar.progressText)
        val = min(globalVar.progressPer, 100)
        self.progress_bar.setValue(val)
        if globalVar.progressPer >= 101 or globalVar.cancelProcess:
            self.timer.stop()
            self.accept()

    def on_cancel(self):
        globalVar.cancelProcess = True
        print("Canceled")
        self.timer.stop()
        self.reject()


class ScientoPyGui(QMainWindow):
    def __init__(self):
        super().__init__()

        self.config = load_config()
        self.scientoPy = ScientoPyClass(from_gui=True)
        self.preprocess = PreProcessClass(from_gui=True)

        self.setWindowTitle("ScientoPy")
        self.setMinimumSize(853, 480)

        # Parse saved geometry
        try:
            w, h = self.config["window_geometry"].split("x")
            self.resize(int(w), int(h))
        except Exception:
            self.resize(1000, 600)

        # Window icon
        icon_path = asset_path("scientopy_icon.png")
        if os.path.exists(icon_path):
            self.setWindowIcon(QIcon(icon_path))

        # Menu bar
        self._create_menu_bar()

        # Central widget with tabs
        central = QWidget()
        self.setCentralWidget(central)
        main_layout = QVBoxLayout(central)
        main_layout.setContentsMargins(4, 4, 4, 4)

        self.tabs = QTabWidget()
        main_layout.addWidget(self.tabs)

        self._create_preprocess_tab()
        self._create_analysis_tab()
        self._create_results_tab()
        self._create_ext_results_tab()

        # Apply saved appearance
        self._apply_appearance(self.config.get("appearance_mode", "System"))

    # ── Menu Bar ──────────────────────────────────────────────

    def _create_menu_bar(self):
        menu_bar = self.menuBar()

        view_menu = menu_bar.addMenu("View")
        appearance_menu = view_menu.addMenu("Appearance")

        self.appearance_group = QActionGroup(self)
        self.appearance_group.setExclusive(True)

        for mode in ("System", "Light", "Dark"):
            action = QAction(mode, self, checkable=True)
            action.setData(mode)
            if mode == self.config.get("appearance_mode", "System"):
                action.setChecked(True)
            action.triggered.connect(lambda checked, m=mode: self._apply_appearance(m))
            self.appearance_group.addAction(action)
            appearance_menu.addAction(action)

    def _apply_appearance(self, mode):
        app = QApplication.instance()
        self.config["appearance_mode"] = mode

        if mode == "System":
            app.setStyleSheet("")
            app.setPalette(app.style().standardPalette())
        elif mode == "Light":
            app.setStyleSheet("")
            app.setPalette(app.style().standardPalette())
        elif mode == "Dark":
            app.setStyleSheet("")
            palette = QPalette()
            CR = QPalette.ColorRole
            palette.setColor(CR.Window, QColor(43, 43, 43))
            palette.setColor(CR.WindowText, QColor(204, 204, 204))
            palette.setColor(CR.Base, QColor(30, 30, 30))
            palette.setColor(CR.AlternateBase, QColor(50, 50, 50))
            palette.setColor(CR.ToolTipBase, QColor(43, 43, 43))
            palette.setColor(CR.ToolTipText, QColor(204, 204, 204))
            palette.setColor(CR.Text, QColor(204, 204, 204))
            palette.setColor(CR.Button, QColor(53, 53, 53))
            palette.setColor(CR.ButtonText, QColor(204, 204, 204))
            palette.setColor(CR.BrightText, QColor(255, 0, 0))
            palette.setColor(CR.Link, QColor(42, 130, 218))
            palette.setColor(CR.Highlight, QColor(42, 130, 218))
            palette.setColor(CR.HighlightedText, QColor(0, 0, 0))
            palette.setColor(CR.PlaceholderText, QColor(130, 130, 130))
            app.setPalette(palette)

        # Update matplotlib theme
        apply_matplotlib_theme(app)

        # Update logo if we have both variants
        self._update_logo()

    def _update_logo(self):
        if not hasattr(self, 'logo_label'):
            return
        app = QApplication.instance()
        dark = is_dark_mode(app)
        dark_logo = asset_path("scientopy_logo_dark.png")
        light_logo = asset_path("scientopy_logo.png")
        logo_path = dark_logo if dark and os.path.exists(dark_logo) else light_logo
        if os.path.exists(logo_path):
            pixmap = QPixmap(logo_path)
            scaled = pixmap.scaled(400, 200, Qt.KeepAspectRatio, Qt.SmoothTransformation)
            self.logo_label.setPixmap(scaled)

    # ── Pre-processing Tab ────────────────────────────────────

    def _create_preprocess_tab(self):
        page = QWidget()
        self.tabs.addTab(page, "1. Pre-processing")
        layout = QVBoxLayout(page)

        # Logo area (centered, stretches)
        logo_container = QVBoxLayout()
        logo_container.addStretch(1)

        self.logo_label = QLabel()
        self.logo_label.setAlignment(Qt.AlignCenter)
        logo_file = asset_path("scientopy_logo.png")
        if os.path.exists(logo_file):
            pixmap = QPixmap(logo_file)
            scaled = pixmap.scaled(400, 200, Qt.KeepAspectRatio, Qt.SmoothTransformation)
            self.logo_label.setPixmap(scaled)
        logo_container.addWidget(self.logo_label)

        version_label = QLabel(
            "Universidad del Cauca, Popayán, Colombia\n"
            "MIT License\n"
            "Version %s" % globalVar.SCIENTOPY_VERSION
        )
        version_label.setAlignment(Qt.AlignCenter)
        logo_container.addWidget(version_label)
        logo_container.addStretch(1)

        layout.addLayout(logo_container, stretch=1)

        # Dataset folder row
        dataset_row = QHBoxLayout()
        dataset_row.addWidget(QLabel("Dataset folder:"))

        self.dataset_entry = QLineEdit()
        if self.config.get("last_dataset_folder"):
            self.dataset_entry.setText(self.config["last_dataset_folder"])
        dataset_row.addWidget(self.dataset_entry, stretch=1)

        browse_btn = QPushButton("Browse")
        browse_btn.clicked.connect(self.select_dataset)
        dataset_row.addWidget(browse_btn)

        layout.addLayout(dataset_row)

        # Bottom row: checkbox + buttons
        bottom_row = QHBoxLayout()

        self.chk_remove_dupl = QCheckBox("Remove duplicated documents")
        self.chk_remove_dupl.setChecked(True)
        bottom_row.addWidget(self.chk_remove_dupl)

        bottom_row.addStretch(1)

        run_preprocess_btn = QPushButton("Run preprocess")
        run_preprocess_btn.clicked.connect(self.run_preprocess)
        bottom_row.addWidget(run_preprocess_btn)

        layout.addLayout(bottom_row)

    # ── Analysis Tab ──────────────────────────────────────────

    def _create_analysis_tab(self):
        page = QWidget()
        self.tabs.addTab(page, "2. Analysis")
        page_layout = QVBoxLayout(page)

        # Splitter: left form | right text area
        splitter = QSplitter(Qt.Horizontal)
        self.analysis_splitter = splitter

        # Left panel: form
        left_widget = QWidget()
        left_layout = QVBoxLayout(left_widget)
        left_layout.setContentsMargins(0, 0, 0, 0)

        form = QFormLayout()

        self.combo_criterion = QComboBox()
        self.combo_criterion.addItems(globalVar.validCriterion)
        self.combo_criterion.setCurrentIndex(3)
        self.combo_criterion.setToolTip(
            "Field to analyze: author, sourceTitle, authorKeywords,\n"
            "indexKeywords, bothKeywords, abstract, documentType,\n"
            "dataBase, country, institution, institutionWithCountry")
        form.addRow("Criterion:", self.combo_criterion)

        self.combo_graph_type = QComboBox()
        self.combo_graph_type.addItems(globalVar.validGrapTypes)
        self.combo_graph_type.setCurrentIndex(0)
        self.combo_graph_type.setToolTip(
            "Visualization type:\n"
            "bar_trends - Horizontal bars with percentage in last years\n"
            "bar - Horizontal bars with total documents\n"
            "time_line - Documents per year line plot\n"
            "evolution - Accumulative documents + AGR vs PDLY scatter\n"
            "word_cloud - Word cloud sized by document count")
        form.addRow("Graph type:", self.combo_graph_type)

        self.spin_start_year = QSpinBox()
        self.spin_start_year.setRange(1900, 2100)
        self.spin_start_year.setValue(globalVar.DEFAULT_START_YEAR)
        self.spin_start_year.setToolTip(
            "Start year for the analysis range.\n"
            "Papers published before this year are excluded.")
        form.addRow("Start Year:", self.spin_start_year)

        self.spin_end_year = QSpinBox()
        self.spin_end_year.setRange(1900, 2100)
        self.spin_end_year.setValue(globalVar.DEFAULT_END_YEAR)
        self.spin_end_year.setToolTip(
            "End year for the analysis range.\n"
            "Papers published after this year are excluded.")
        form.addRow("End Year:", self.spin_end_year)

        self.spin_topics_length = QSpinBox()
        self.spin_topics_length.setRange(0, 1000)
        self.spin_topics_length.setValue(10)
        self.spin_topics_length.setToolTip(
            "Number of top topics to extract and display.\n"
            "Default: 10")
        form.addRow("Topics length:", self.spin_topics_length)

        self.spin_skip_first = QSpinBox()
        self.spin_skip_first.setRange(0, 1000)
        self.spin_skip_first.setValue(0)
        self.spin_skip_first.setToolTip(
            "Skip the first N topics from the results.\n"
            "Useful to filter dominant topics that overshadow others.\n"
            "Default: 0")
        form.addRow("Skip first:", self.spin_skip_first)

        self.spin_window_width = QSpinBox()
        self.spin_window_width.setRange(1, 100)
        self.spin_window_width.setValue(2)
        self.spin_window_width.setToolTip(
            "Window width in years for AGR, ADY, and PDLY calculation.\n"
            "Start year for indicators: Ys = EndYear - (WindowWidth + 1)\n"
            "Default: 2")
        form.addRow("Window (years):", self.spin_window_width)

        left_layout.addLayout(form)

        self.chk_previous_results = QCheckBox("Use previous results")
        self.chk_previous_results.setToolTip(
            "Analyze based on the output documents from the last run.\n"
            "For example, first extract papers from a country, then\n"
            "use previous results to find top keywords within that subset.")
        left_layout.addWidget(self.chk_previous_results)

        self.chk_trend_analysis = QCheckBox("Trend analysis")
        self.chk_trend_analysis.setToolTip(
            "Find trending topics based on the highest Average Growth Rate (AGR).\n"
            "Extracts the top 200 topics, calculates AGR for the window period,\n"
            "and sorts them from highest to lowest AGR.")
        left_layout.addWidget(self.chk_trend_analysis)

        left_layout.addStretch(1)

        left_widget.setMinimumWidth(250)
        left_widget.setMaximumWidth(350)

        # Right panel: custom topics
        right_widget = QWidget()
        right_layout = QVBoxLayout(right_widget)
        right_layout.setContentsMargins(0, 0, 0, 0)

        right_layout.addWidget(QLabel("Custom topics:"))

        self.custom_topics = QPlainTextEdit()
        right_layout.addWidget(self.custom_topics, stretch=1)

        splitter.addWidget(left_widget)
        splitter.addWidget(right_widget)

        # Restore splitter sizes
        try:
            sizes = self.config.get("splitter_sizes", [280, 600])
            splitter.setSizes(sizes)
        except Exception:
            splitter.setSizes([280, 600])

        page_layout.addWidget(splitter, stretch=1)

        # Bottom button bar
        btn_row = QHBoxLayout()

        bibtex_btn = QPushButton("Generate BibTeX")
        bibtex_btn.setToolTip(
            "Generate a BibTeX bibliography file from a LaTeX document.\n"
            "Select a .tex file that uses paper EIDs as \\cite{} keys.\n"
            "The .bib file is created next to the input file.")
        bibtex_btn.clicked.connect(self.generate_bibtex)
        btn_row.addWidget(bibtex_btn)

        btn_row.addStretch(1)

        run_btn = QPushButton("Run")
        run_btn.clicked.connect(self.scientoPyRun)
        btn_row.addWidget(run_btn)

        page_layout.addLayout(btn_row)

    # ── Results Tab ────────────────────────────────────────────

    def _create_results_tab(self):
        page = QWidget()
        self.tabs.addTab(page, "3. Results")
        layout = QVBoxLayout(page)

        self.results_table = QTableWidget()
        self.results_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.results_table.setAlternatingRowColors(True)
        self.results_table.setSelectionMode(QTableWidget.SelectionMode.ExtendedSelection)
        self.results_table.setSortingEnabled(True)
        layout.addWidget(self.results_table)

        # Ctrl+C to copy selected cells
        copy_shortcut = QShortcut(QKeySequence.StandardKey.Copy, self.results_table)
        copy_shortcut.activated.connect(self._copy_selected_cells)

        # Bottom bar: status label + copy buttons
        bottom_row = QHBoxLayout()

        self.results_status_label = QLabel("No results yet. Run preprocessing first.")
        bottom_row.addWidget(self.results_status_label, stretch=1)

        copy_sel_btn = QPushButton("Copy Selection")
        copy_sel_btn.clicked.connect(self._copy_selected_cells)
        bottom_row.addWidget(copy_sel_btn)

        copy_all_btn = QPushButton("Copy All")
        copy_all_btn.clicked.connect(self._copy_all_cells)
        bottom_row.addWidget(copy_all_btn)

        layout.addLayout(bottom_row)

        # Load existing results if available
        if os.path.exists(self.scientoPy.preprocessBriefFileName):
            self._load_results_table()

    def _load_results_table(self, filepath=None):
        if filepath is None:
            filepath = self.scientoPy.preprocessBriefFileName
        if not os.path.exists(filepath):
            return

        with open(filepath, "r", newline="", encoding="utf-8") as f:
            reader = csv.reader(f)
            rows = list(reader)

        if not rows:
            return

        headers = rows[0]
        data = rows[1:]

        self.results_table.setSortingEnabled(False)

        self.results_table.setColumnCount(len(headers))
        self.results_table.setRowCount(len(data))
        self.results_table.setHorizontalHeaderLabels(headers)

        for c, header in enumerate(headers):
            item = self.results_table.horizontalHeaderItem(c)
            if item:
                item.setToolTip(self._get_header_tooltip(header))

        for r, row in enumerate(data):
            for c, cell in enumerate(row):
                text = cell.strip()
                try:
                    float(text)
                    item = NumericTableWidgetItem(text)
                    item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)
                except ValueError:
                    item = QTableWidgetItem(text)
                self.results_table.setItem(r, c, item)

        self.results_table.setSortingEnabled(True)

        for col in range(len(headers)):
            self.results_table.horizontalHeader().setSectionResizeMode(
                col, QHeaderView.ResizeMode.ResizeToContents
            )

        self.results_table.resizeRowsToContents()
        self.results_status_label.setText(
            "Showing results from: %s" % os.path.basename(filepath)
        )

    @staticmethod
    def _get_header_tooltip(header):
        tip = HEADER_TOOLTIPS.get(header, "")
        if not tip and header.startswith("Topic "):
            criterion = header[len("Topic "):]
            tip = HEADER_TOOLTIPS.get(criterion, "")
            if tip:
                tip = "Topic: " + tip
        return tip

    # ── Extended Results Tab ─────────────────────────────────

    def _create_ext_results_tab(self):
        page = QWidget()
        self.tabs.addTab(page, "4. Extended Results")
        layout = QVBoxLayout(page)

        self.ext_results_table = QTableWidget()
        self.ext_results_table.setEditTriggers(QTableWidget.EditTrigger.NoEditTriggers)
        self.ext_results_table.setAlternatingRowColors(True)
        self.ext_results_table.setSelectionMode(QTableWidget.SelectionMode.ExtendedSelection)
        self.ext_results_table.setSortingEnabled(True)
        layout.addWidget(self.ext_results_table)

        copy_shortcut = QShortcut(QKeySequence.StandardKey.Copy, self.ext_results_table)
        copy_shortcut.activated.connect(self._copy_selected_ext_cells)

        bottom_row = QHBoxLayout()

        self.ext_results_status_label = QLabel("No extended results yet. Run analysis first.")
        bottom_row.addWidget(self.ext_results_status_label, stretch=1)

        copy_sel_btn = QPushButton("Copy Selection")
        copy_sel_btn.clicked.connect(self._copy_selected_ext_cells)
        bottom_row.addWidget(copy_sel_btn)

        copy_all_btn = QPushButton("Copy All")
        copy_all_btn.clicked.connect(self._copy_all_ext_cells)
        bottom_row.addWidget(copy_all_btn)

        layout.addLayout(bottom_row)

    def _load_ext_results_table(self, filepath):
        if not os.path.exists(filepath):
            return

        with open(filepath, "r", newline="", encoding="utf-8") as f:
            reader = csv.reader(f)
            rows = list(reader)

        if not rows:
            return

        headers = rows[0]
        data = rows[1:]

        self.ext_results_table.setSortingEnabled(False)

        self.ext_results_table.setColumnCount(len(headers))
        self.ext_results_table.setRowCount(len(data))
        self.ext_results_table.setHorizontalHeaderLabels(headers)

        for c, header in enumerate(headers):
            item = self.ext_results_table.horizontalHeaderItem(c)
            if item:
                item.setToolTip(self._get_header_tooltip(header))

        for r, row in enumerate(data):
            for c, cell in enumerate(row):
                text = cell.strip()
                try:
                    float(text)
                    item = NumericTableWidgetItem(text)
                    item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)
                except ValueError:
                    item = QTableWidgetItem(text)
                self.ext_results_table.setItem(r, c, item)

        self.ext_results_table.setSortingEnabled(True)

        for col in range(len(headers)):
            self.ext_results_table.horizontalHeader().setSectionResizeMode(
                col, QHeaderView.ResizeMode.ResizeToContents
            )

        self.ext_results_table.resizeRowsToContents()
        self.ext_results_status_label.setText(
            "Showing extended results from: %s" % os.path.basename(filepath)
        )

    # ── Copy Helpers ──────────────────────────────────────────

    @staticmethod
    def _copy_selected_from(table):
        selection = table.selectedIndexes()
        if not selection:
            return

        rows_dict = {}
        for idx in selection:
            rows_dict.setdefault(idx.row(), {})[idx.column()] = idx.data() or ""

        min_col = min(c for cols in rows_dict.values() for c in cols)
        max_col = max(c for cols in rows_dict.values() for c in cols)

        lines = []
        headers = []
        for c in range(min_col, max_col + 1):
            item = table.horizontalHeaderItem(c)
            headers.append(item.text() if item else "")
        lines.append("\t".join(headers))

        for r in sorted(rows_dict):
            cells = []
            for c in range(min_col, max_col + 1):
                cells.append(rows_dict[r].get(c, ""))
            lines.append("\t".join(cells))

        QApplication.clipboard().setText("\n".join(lines))

    @staticmethod
    def _copy_all_from(table):
        if table.rowCount() == 0:
            return

        lines = []
        headers = []
        for c in range(table.columnCount()):
            item = table.horizontalHeaderItem(c)
            headers.append(item.text() if item else "")
        lines.append("\t".join(headers))

        for r in range(table.rowCount()):
            cells = []
            for c in range(table.columnCount()):
                item = table.item(r, c)
                cells.append(item.text() if item else "")
            lines.append("\t".join(cells))

        QApplication.clipboard().setText("\n".join(lines))

    def _copy_selected_cells(self):
        self._copy_selected_from(self.results_table)

    def _copy_all_cells(self):
        self._copy_all_from(self.results_table)

    def _copy_selected_ext_cells(self):
        self._copy_selected_from(self.ext_results_table)

    def _copy_all_ext_cells(self):
        self._copy_all_from(self.ext_results_table)

    # ── Actions ───────────────────────────────────────────────

    def select_dataset(self):
        dir_name = QFileDialog.getExistingDirectory(self, "Select dataset folder")
        if dir_name:
            self.dataset_entry.setText(dir_name)
            self.config["last_dataset_folder"] = dir_name

    def open_results(self):
        if os.path.exists(self.scientoPy.resultsFileName):
            webbrowser.open(self.scientoPy.resultsFileName)
        else:
            QMessageBox.critical(self, "Error", "No results found, please run the analysis first")

    def open_ext_results(self):
        if os.path.exists(self.scientoPy.extResultsFileName):
            webbrowser.open(self.scientoPy.extResultsFileName)
        else:
            QMessageBox.critical(self, "Error", "No extended results found, please run the analysis first")

    def open_preprocess_brief(self):
        if os.path.exists(self.scientoPy.preprocessBriefFileName):
            webbrowser.open(self.scientoPy.preprocessBriefFileName)
        else:
            QMessageBox.critical(self, "Error", "No preprocess brief found, please run the preprocess first")

    def run_preprocess(self):
        dataset_path = self.dataset_entry.text()
        if not dataset_path:
            QMessageBox.critical(self, "Error", "No dataset folder defined")
            return

        try:
            self.preprocess.dataInFolder = dataset_path
            self.preprocess.noRemDupl = not self.chk_remove_dupl.isChecked()

            globalVar.cancelProcess = False
            globalVar.progressPer = 0

            t1 = threading.Thread(target=self.preprocess.preprocess)
            t1.start()

            dialog = ProgressDialog(self)
            dialog.exec()

            t1.join()

            if globalVar.cancelProcess:
                QMessageBox.critical(self, "Error", "Preprocessing canceled")
            elif globalVar.totalPapers > 0:
                apply_matplotlib_theme(QApplication.instance())
                self.preprocess.graphBrief()
                self._load_results_table()
                self.tabs.setCurrentIndex(2)  # Switch to Results tab
            elif globalVar.totalPapers == 0:
                QMessageBox.critical(self, "Error",
                                     "No valid dataset files found in: %s" % dataset_path)
        except FileNotFoundError:
            QMessageBox.critical(self, "Error", "Dataset folder not found: %s" % dataset_path)
        except PermissionError:
            QMessageBox.critical(self, "Error", "Permission denied accessing: %s" % dataset_path)
        except Exception as e:
            QMessageBox.critical(self, "Error", "Preprocessing failed: %s" % str(e))

    def scientoPyRun(self):
        globalVar.cancelProcess = False
        globalVar.progressPer = 0

        if not os.path.exists(self.scientoPy.preprocessDatasetFile):
            QMessageBox.critical(self, "Error",
                                 "No preprocess input dataset, please run the preprocess first")
            return

        print(self.chk_previous_results.isChecked())

        self.scientoPy.closePlot()

        self.scientoPy.criterion = self.combo_criterion.currentText()
        self.scientoPy.graphType = self.combo_graph_type.currentText()
        self.scientoPy.startYear = self.spin_start_year.value()
        self.scientoPy.endYear = self.spin_end_year.value()
        self.scientoPy.length = self.spin_topics_length.value()
        self.scientoPy.skipFirst = self.spin_skip_first.value()
        self.scientoPy.windowWidth = self.spin_window_width.value()
        self.scientoPy.previousResults = self.chk_previous_results.isChecked()
        self.scientoPy.trend = self.chk_trend_analysis.isChecked()

        topics_text = self.custom_topics.toPlainText().strip()
        if topics_text:
            self.scientoPy.topics = topics_text.replace("\n", ";")
        else:
            self.scientoPy.topics = ''

        self._thread_error = None

        def run_analysis():
            try:
                self.scientoPy.scientoPy()
            except ScientoPyError as e:
                self._thread_error = str(e)

        t1 = threading.Thread(target=run_analysis)
        t1.start()

        dialog = ProgressDialog(self)
        dialog.exec()

        t1.join()

        if globalVar.cancelProcess:
            return

        if self._thread_error:
            QMessageBox.critical(self, "Error", self._thread_error)
            return

        apply_matplotlib_theme(QApplication.instance())
        self.scientoPy.plotResults()

        if self.scientoPy.resultsFileName:
            self._load_results_table(self.scientoPy.resultsFileName)
        if self.scientoPy.extResultsFileName:
            self._load_ext_results_table(self.scientoPy.extResultsFileName)
        if self.scientoPy.resultsFileName:
            self.tabs.setCurrentIndex(2)  # Switch to Results tab

    def generate_bibtex(self):
        if not os.path.exists(self.scientoPy.preprocessDatasetFile):
            QMessageBox.critical(self, "Error",
                                 "No preprocess input dataset, please run the preprocess first")
            return

        latex_file, _ = QFileDialog.getOpenFileName(
            self, "Select the LaTeX file", "./",
            "LaTeX files (*.tex);;All files (*.*)"
        )
        if not latex_file:
            return

        print(latex_file)
        out_file = generateBibtex(latex_file)
        abs_path = os.path.abspath(out_file)

        msg = QMessageBox(self)
        msg.setIcon(QMessageBox.Icon.Information)
        msg.setWindowTitle("BibTeX Generated")
        msg.setText("BibTeX file created successfully.")
        msg.setInformativeText(
            '<a href="file://%s">%s</a>' % (abs_path, abs_path)
        )
        msg.setTextFormat(Qt.TextFormat.RichText)
        msg.setTextInteractionFlags(Qt.TextInteractionFlag.TextBrowserInteraction)
        open_btn = msg.addButton("Open File", QMessageBox.ButtonRole.ActionRole)
        msg.addButton(QMessageBox.StandardButton.Ok)
        msg.exec()

        if msg.clickedButton() == open_btn:
            webbrowser.open(abs_path)

    # ── Close / Save Config ───────────────────────────────────

    def closeEvent(self, event):
        self.config["window_geometry"] = "%dx%d" % (self.width(), self.height())
        if hasattr(self, 'analysis_splitter'):
            self.config["splitter_sizes"] = self.analysis_splitter.sizes()
        save_config(self.config)
        event.accept()


def runGui():
    app = QApplication(sys.argv)
    app.setApplicationName("ScientoPy")

    window = ScientoPyGui()
    window.show()

    sys.exit(app.exec())


if __name__ == '__main__':
    runGui()
